### PR TITLE
Unmarshallers fail with NoContentException on empty entity (#88)

### LINKED ISSUE #88: NoContentException should be thrown to signal empty entity
The `NoContentException` exception is defined by akka-http and is used by unmarshallers to signal the entity was unexpectedly empty.

The current behaviour in the different sub-projects is to let the underlying library to fail. It means a poor exception with no integration with akka-http (something like `Unexpected end of input`).

The `NoContentException` exception is already used in directives to handle nicely this error. For example the `entity()` directive will reject the request with `RequestEntityExpectedRejection`. 

Note that the empty entity can never be a valid json value. If  `null` is expected the string `null` must be in the entity and is not the same as an empty one.

This change could possibly break user code as the exception in case of empty entity won't be the same.

### PR DESCRIPTION
**Pull request by lomigmegard**
Fixes #88 

Other changes:
* added one more test to ensure the `application/json` media-type is requested by the unmarshaller.
* Factorized the `jsonStringUnmarshaller` and `jsonStringMarshaller`. This is thread safe and should be more efficient.

### CODE REVIEW

File: akka-http-circe/src/main/scala/de/heikoseeberger/akkahttpcirce/CirceSupport.scala [hunk 1]
```diff
@@ -67,9 +72,7 @@ trait CirceSupport {
     */
   implicit def circeToEntityMarshaller[A](
       implicit encoder: Encoder[A],
-      printer: Json => String = Printer.noSpaces.pretty
+      printer: Json ⇒ String = Printer.noSpaces.pretty
   ): ToEntityMarshaller[A] =
-    Marshaller.StringMarshaller
-      .wrap(`application/json`)(printer)
-      .compose(encoder.apply)
+    jsonStringMarshaller.compose(printer).compose(encoder.apply)
```
Comment (hseeberger) [inline akka-http-circe/src/main/scala/de/heikoseeberger/akkahttpcirce/CirceSupport.scala]: What's the exact difference btw. the new and old implementation? Please notice that the old implementation follows [SprayJsonSupport](https://github.com/akka/akka/blob/master/akka-http-marshallers-scala/akka-http-spray-json/src/main/scala/akka/http/scaladsl/marshallers/sprayjson/SprayJsonSupport.scala).

File: akka-http-argonaut/src/main/scala/de/heikoseeberger/akkahttpargonaut/ArgonautSupport.scala [hunk 2]
```diff
@@ -22,7 +22,9 @@ import akka.http.scaladsl.unmarshalling.{
   FromEntityUnmarshaller,
   Unmarshaller
 }
+import akka.util.ByteString
 import argonaut.{ DecodeJson, EncodeJson, Json, Parse, PrettyParams }
+
```
Comment (hseeberger) [inline akka-http-argonaut/src/main/scala/de/heikoseeberger/akkahttpargonaut/ArgonautSupport.scala]: No blank lines in import blocks.

File: akka-http-argonaut/src/main/scala/de/heikoseeberger/akkahttpargonaut/ArgonautSupport.scala [hunk 3]
```diff
@@ -22,7 +22,9 @@ import akka.http.scaladsl.unmarshalling.{
...
 import scalaz.Scalaz._
```
Comment (hseeberger) [inline akka-http-argonaut/src/main/scala/de/heikoseeberger/akkahttpargonaut/ArgonautSupport.scala]: No global wildcard imports.

File: akka-http-argonaut/src/main/scala/de/heikoseeberger/akkahttpargonaut/ArgonautSupport.scala [hunk 4]
```diff
@@ -39,8 +41,19 @@ object ArgonautSupport extends ArgonautSupport
...
+        case (ByteString.empty, _) ⇒ throw Unmarshaller.NoContentException
+        case (data, charset)       ⇒ data.decodeString(charset.nioCharset.name)
+      }
+
+  private val jsonStringMarshaller: ToEntityMarshaller[String] =
+    Marshaller.stringMarshaller(`application/json`)
+
   /**
-    * HTTP entity => `A`
+    * HTTP entity ⇒ `A`
```
Comment (hseeberger) [inline akka-http-argonaut/src/main/scala/de/heikoseeberger/akkahttpargonaut/ArgonautSupport.scala]: Don't rewrite arrows.

File: akka-http-argonaut/src/main/scala/de/heikoseeberger/akkahttpargonaut/ArgonautSupport.scala [hunk 5]
```diff
@@ -39,8 +41,19 @@ object ArgonautSupport extends ArgonautSupport
   */
 trait ArgonautSupport {
 
+  private val jsonStringUnmarshaller: FromEntityUnmarshaller[String] =
```
Comment (hseeberger) [inline akka-http-argonaut/src/main/scala/de/heikoseeberger/akkahttpargonaut/ArgonautSupport.scala]: No type annotation for private members.

**Comment by hseeberger** [comment]
Thanks a lot!

I have one substantial question and some code style remarks. Please clarify / change.

File: akka-http-argonaut/src/main/scala/de/heikoseeberger/akkahttpargonaut/ArgonautSupport.scala (hunk 2 above)
Comment (lomigmegard) [inline akka-http-argonaut/src/main/scala/de/heikoseeberger/akkahttpargonaut/ArgonautSupport.scala]: done

File: akka-http-argonaut/src/main/scala/de/heikoseeberger/akkahttpargonaut/ArgonautSupport.scala (hunk 3 above)
Comment (lomigmegard) [inline akka-http-argonaut/src/main/scala/de/heikoseeberger/akkahttpargonaut/ArgonautSupport.scala]: done

File: akka-http-argonaut/src/main/scala/de/heikoseeberger/akkahttpargonaut/ArgonautSupport.scala (hunk 5 above)
Comment (lomigmegard) [inline akka-http-argonaut/src/main/scala/de/heikoseeberger/akkahttpargonaut/ArgonautSupport.scala]: done

File: akka-http-argonaut/src/main/scala/de/heikoseeberger/akkahttpargonaut/ArgonautSupport.scala (hunk 4 above)
Comment (lomigmegard) [inline akka-http-argonaut/src/main/scala/de/heikoseeberger/akkahttpargonaut/ArgonautSupport.scala]: reverted

File: akka-http-circe/src/main/scala/de/heikoseeberger/akkahttpcirce/CirceSupport.scala (hunk 1 above)
Comment (lomigmegard) [inline akka-http-circe/src/main/scala/de/heikoseeberger/akkahttpcirce/CirceSupport.scala]: The behaviour is exactly the same.
The change hopefully makes the code more readable, but more importantly it should be more efficient (even if not benchmarked). 

The call to `Marshaller.StringMarshaller.wrap(``application/json``)` is simply factorized into a val to skip to compute over and over again the same value. The trade-off with the memory is worth it as it's one object in memory for all the application life.

I talked with Konrad Malawski regarding this on Gitter, he agreed that it will prevent some object allocation (and it's safe). The impact must be tiny though. Since it doesn't hurt the code clarity I included the change.

Comment (hseeberger) [inline akka-http-circe/src/main/scala/de/heikoseeberger/akkahttpcirce/CirceSupport.scala]: Thanks for the explanation. I already did get your point about possibly improving performance via factoring out the marshallers. What I'd like to understand is the difference btw. `Marshaller.stringMarshaller(`application/json`)` and `Marshaller.StringMarshaller.wrap(`application/json`)`.

Comment (hseeberger) [inline akka-http-circe/src/main/scala/de/heikoseeberger/akkahttpcirce/CirceSupport.scala]: OK, I looked it up. Your way makes more sense ;-)

**Comment by hseeberger** [comment]
Thanks a lot!

**Comment by hseeberger** [comment]
Published version 1.10.0-1-ga514d78 (to Bintray). Let me know if it works for you.

**Comment by lomigmegard** [comment]
Thanks for the merge!
I don't have a project setup right now to test it. But with the unit tests I am confident it will work :)

I have a couple of other ideas, will create the PR in the coming days/weeks.
